### ISSUE TITLE
package.json incompatible with latest version of coffeescript

### ISSUE THREAD

**Issue by bsklaroff** [Koronen/coffeelint-conditional-modifiers#1]
When I run 'npm install --save-dev coffeelint-conditional-modifiers' inside my current project, I get the following error:

npm ERR! peerinvalid The package coffeelint does not satisfy its siblings' peerDependencies requirements!

Can you please change the package.json so this package is compatible with coffeescript version ~1?

**Comment by Koronen** [comment]
This sounds like reasonable request. I'll make that change.

**Comment by bsklaroff** [comment]
thanks for the quick turnaround on this
